cloudforet-io/plugin-google-cloud-inven-collector

.gitignore

chore: add .idea in gitignore

---

src/spaceone/inventory/manager/compute_engine/vm_instance/vm_instance_manager_resource_helper.py
src/spaceone/inventory/model/compute_engine/disk/cloud_service_type.py
src/spaceone/inventory/model/compute_engine/instance/cloud_service_type.py

bugfix: fix Disk and Instance field of metadata in ComputeEngine

---

src/spaceone/inventory/model/compute_engine/instance/cloud_service_type.py

bugfix: fix instance state in cloud_service_type in ComputeEngine

---

src/spaceone/inventory/model/compute_engine/instance/cloud_service_type.py

bugfix: change instance state in cloud_service_type in ComputeEngine

---

src/spaceone/inventory/manager/compute_engine/vm_instance/vm_instance_manager_resource_helper.py
test/api/test_cloudservice_api.py

bugfix: fix cos os in vm_instance of ComputeEngine

---

src/spaceone/inventory/model/pub_sub/schema/cloud_service.py
src/spaceone/inventory/model/pub_sub/schema/cloud_service_type.py
src/spaceone/inventory/model/pub_sub/snapshot/cloud_service.py
src/spaceone/inventory/model/pub_sub/snapshot/cloud_service_type.py
src/spaceone/inventory/model/pub_sub/subscription/cloud_service.py
src/spaceone/inventory/model/pub_sub/subscription/cloud_service_type.py
src/spaceone/inventory/model/pub_sub/topic/cloud_service.py
src/spaceone/inventory/model/pub_sub/topic/cloud_service_type.py
src/spaceone/inventory/model/pub_sub/topic/data.py

* Check that all planned fields are exposed normally
* Changed to work normally for Int field of Search function
* add push endpoint field in subscription in Pub/Sub
* #8

bugfix: verify that all planned fields are exposed normally (#8)

---

src/spaceone/inventory/manager/pub_sub/topic_manager.py
src/spaceone/inventory/model/pub_sub/topic/cloud_service.py
src/spaceone/inventory/model/pub_sub/topic/data.py

* As you can see in the picture above, the problem that subscription_id does not appear has been resolved.
* #8

bugfix: make subcription_id field in details tab of topic (#8)

---

README.md

Signed-off-by: Seolmin Kwon <seolmin@mz.co.kr>
As the Pub/Sub service has been developed, README.md has been updated.
The list below has been updated.
* Contents
* IAM and Service Endpoint
* Service list
* #8

docs: add information of Pub/Sub in README.md (#8)

---

README.md

write service endpoint in README.md

write service endpoint in README.md

---

src/spaceone/inventory/manager/cloud_functions/function_manager.py
src/spaceone/inventory/model/cloud_functions/function/cloud_service.py
src/spaceone/inventory/model/cloud_functions/function/data.py

Signed-off-by: Seolmin Kwon <seolmin@mz.co.kr>
Changed the types of runtime_environment_variables and build_environment_variables from dict to list of dict.
* #22

modify variable tab by changing type in cloud functions

---

src/spaceone/inventory/libs/schema/metadata/dynamic_layout.py
src/spaceone/inventory/model/cloud_functions/function/cloud_service.py

Signed-off-by: Seolmin Kwon <seolmin@mz.co.kr>
The set_field method of the existing dynamic layout was used.
* #21

Use set_field method to source_code field in cloud functions

---

src/spaceone/inventory/manager/cloud_functions/function_gen1_manager.py
src/spaceone/inventory/manager/cloud_functions/function_gen2_manager.py
src/spaceone/inventory/model/cloud_functions/function_gen1/cloud_service_type.py
src/spaceone/inventory/model/cloud_functions/function_gen1/data.py
src/spaceone/inventory/model/cloud_functions/function_gen2/cloud_service.py
src/spaceone/inventory/model/cloud_functions/function_gen2/cloud_service_type.py

* Fixed various bugs in metadata.
* #19

Modify metadata in cloud functions

---

src/spaceone/inventory/manager/cloud_functions/function_gen1_manager.py
src/spaceone/inventory/manager/cloud_functions/function_gen2_manager.py
src/spaceone/inventory/model/cloud_functions/function_gen1/cloud_service_type.py
src/spaceone/inventory/model/cloud_functions/function_gen1/data.py
src/spaceone/inventory/model/cloud_functions/function_gen2/cloud_service_type.py
src/spaceone/inventory/model/cloud_functions/function_gen2/data.py

* Modify status and executed_function fields of table in cloud functions
* #19

Modify status and executed_function fields of table in cloud functions

---

src/spaceone/inventory/manager/cloud_functions/function_gen1_manager.py

Create event_provider field in 1st generation of cloud functions
* #19

Create event_provider field in 1st generation of cloud functions

---

src/spaceone/inventory/manager/cloud_functions/function_gen1_manager.py

fix typo entry_point t0 entryPoint
```
'executed_function': function.get('entryPoint'),
```
* #19

Fix typo in 1st generation of cloud functions

---

src/spaceone/inventory/libs/schema/metadata/dynamic_layout.py
src/spaceone/inventory/model/cloud_functions/function_gen1/cloud_service.py
src/spaceone/inventory/model/cloud_functions/function_gen2/cloud_service.py

Signed-off-by: Seolmin Kwon <seolmin@mz.co.kr>
create set_code_field method for creating source code tap in cloud functions
* #21

create set_code_field method for creating source code tap in cloud functions

---

README.md

Add cloud functions to service list, IAM and Service Endpoint.
* #13

Add documentation of cloud functions in README.md

---

src/spaceone/inventory/manager/cloud_functions/function_gen2_manager.py

Signed-off-by: seolmin <seolmin@megazone.com>
add except logic of make_memory method in cloud functions

add except logic of make_memory method in cloud functions

---

src/spaceone/inventory/manager/cloud_functions/function_gen1_manager.py
src/spaceone/inventory/manager/cloud_functions/function_gen2_manager.py

Signed-off-by: seolmin <seolmin@megazone.com>
* modify logic to collect 2nd generation cloud functions
* add Node.js 18 key in runtime_map in gen1, gen2 of cloud functions
* modify the logic according to the change from v2's get and list methods to providing function gen1

modify logic to collect 2nd generation cloud functions

---

src/spaceone/inventory/conf/cloud_service_conf.py
src/spaceone/inventory/libs/manager.py
src/spaceone/inventory/model/bigquery/sql_workspace/cloud_service_type.py
src/spaceone/inventory/model/cloud_functions/function_gen1/cloud_service_type.py
src/spaceone/inventory/model/cloud_functions/function_gen2/cloud_service_type.py
src/spaceone/inventory/model/cloud_sql/instance/cloud_service_type.py
src/spaceone/inventory/model/cloud_storage/bucket/cloud_service_type.py
src/spaceone/inventory/model/compute_engine/disk/cloud_service_type.py
src/spaceone/inventory/model/compute_engine/instance/cloud_service_type.py
src/spaceone/inventory/model/compute_engine/instance_group/cloud_service_type.py
src/spaceone/inventory/model/compute_engine/instance_template/cloud_service_type.py
src/spaceone/inventory/model/compute_engine/machine_image/cloud_service_type.py
src/spaceone/inventory/model/compute_engine/snapshot/cloud_service_type.py
src/spaceone/inventory/model/networking/external_ip_address/cloud_service_type.py
src/spaceone/inventory/model/networking/firewall/cloud_service_type.py
src/spaceone/inventory/model/networking/load_balancing/cloud_service_type.py
src/spaceone/inventory/model/networking/route/cloud_service_type.py
src/spaceone/inventory/model/networking/vpc_network/cloud_service_type.py
src/spaceone/inventory/model/pub_sub/schema/cloud_service_type.py
src/spaceone/inventory/model/pub_sub/snapshot/cloud_service_type.py
src/spaceone/inventory/model/pub_sub/subscription/cloud_service_type.py
src/spaceone/inventory/model/pub_sub/topic/cloud_service_type.py
test/api/test_cloudservice_api.py

Signed-off-by: seolmin <seolmin@megazone.com>
* add options to dynamically receive icon url
* When executing the collect method, if there is a custom_asset_url option, change the path of the icon.

add options to dynamically receive icon url

---

README.md
test/api/test_cloudservice_api.py

Signed-off-by: seolmin <seolmin@megazone.com>
* add guide of custom_asset_url option in README.md

add guide of custom_asset_url option in README.md

---

src/spaceone/inventory/model/recommender/insight/data.py
src/spaceone/inventory/model/recommender/recommendation/data.py

* Change the type to accept all types in insight, recommendation model

Change the type to accept all types in insight, recommendation model

---

src/spaceone/inventory/model/recommender/insight/data.py
src/spaceone/inventory/model/recommender/recommendation/data.py

* add dict type to accept all types in insight, recommendation model

add dict type to accept all types in insight, recommendation model

---

src/spaceone/inventory/model/recommender/insight/data.py
src/spaceone/inventory/model/recommender/recommendation/data.py

* Add list type to accept all types in insight, recommendation model

Add list type to accept all types in insight, recommendation model

---

src/spaceone/inventory/manager/recommender/recommender_manager.py
src/spaceone/inventory/model/recommender/insight/data.py
src/spaceone/inventory/model/recommender/recommendation/data.py

* Add IP address insight model because of raising error in insight model

Add IP address insight model because of raising error in insight model

---

src/spaceone/inventory/manager/recommender/recommender_manager.py
src/spaceone/inventory/model/recommender/recommendation/cloud_sevice_type.py

* change cloud_service_type when collecting Recommendation resources in recommender service

Change cloud_service_type when collecting Recommendation resources in recommender service

---

src/spaceone/inventory/conf/cloud_service_conf.py
src/spaceone/inventory/manager/__init__.py
src/spaceone/inventory/manager/recommender/insight_manager.py
src/spaceone/inventory/manager/recommender/recommendation_manager.py
src/spaceone/inventory/model/recommender/recommendation/cloud_sevice_type.py

* Separate the manager of the insight and recommendation processing part of the recommender service

Separate the manager of the insight and recommendation processing part of the recommender service

---

src/spaceone/inventory/model/recommender/__init__.py
src/spaceone/inventory/model/recommender/insight/cloud_service_type.py
src/spaceone/inventory/model/recommender/insight/data.py
src/spaceone/inventory/model/recommender/recommendation/cloud_sevice_type.py

* Delete display_name of tags in recommender service

Delete display_name of tags in recommender service

---

src/spaceone/inventory/manager/recommender/insight_manager.py
src/spaceone/inventory/manager/recommender/recommendation_manager.py

* Change the recommendation's cloud_service_type collection logic

Change the recommendation's cloud_service_type collection logic

---

src/spaceone/inventory/libs/schema/metadata/dynamic_field.py
src/spaceone/inventory/manager/recommender/insight_manager.py
src/spaceone/inventory/manager/recommender/recommendation_manager.py
src/spaceone/inventory/model/recommender/insight/cloud_service.py
src/spaceone/inventory/model/recommender/insight/cloud_service_type.py
src/spaceone/inventory/model/recommender/insight/data.py
src/spaceone/inventory/model/recommender/recommendation/cloud_service.py
src/spaceone/inventory/model/recommender/recommendation/cloud_sevice_type.py
src/spaceone/inventory/model/recommender/recommendation/data.py

* Modify occurred errors in recommender resources

Modify occurred errors in recommender resources

---

src/spaceone/inventory/libs/schema/metadata/dynamic_field.py
src/spaceone/inventory/model/recommender/insight/cloud_service.py
src/spaceone/inventory/model/recommender/insight/cloud_service_type.py
src/spaceone/inventory/model/recommender/recommendation/cloud_service.py
src/spaceone/inventory/model/recommender/recommendation/cloud_sevice_type.py
src/spaceone/inventory/model/recommender/recommendation/data.py

* Fix an issue where the priority level field was not visible in recommendation resource

Fix an issue where the priority level field was not visible in recommendation resource

---

src/spaceone/inventory/model/recommender/recommendation/cloud_service.py
src/spaceone/inventory/model/recommender/recommendation/cloud_sevice_type.py
src/spaceone/inventory/model/recommender/recommendation/data.py

* add resource search field in recommendation resource

Add resource search field in recommendation resource

---

src/spaceone/inventory/model/recommender/insight/cloud_service.py
src/spaceone/inventory/model/recommender/recommendation/cloud_service.py
src/spaceone/inventory/model/recommender/recommendation/cloud_sevice_type.py

* apply link processing between insight and recommendation

Apply link processing between insight and recommendation

---

src/spaceone/inventory/manager/recommender/recommendation_manager.py
src/spaceone/inventory/model/recommender/insight/data.py
src/spaceone/inventory/model/recommender/recommendation/cloud_sevice_type.py
src/spaceone/inventory/model/recommender/recommendation/data.py

* modify change_resource method in recommendation resource
* apply link to related resource field

Modify change_resource method in recommendation resource

---

src/spaceone/inventory/manager/recommender/insight_manager.py
src/spaceone/inventory/model/recommender/insight/cloud_service.py
src/spaceone/inventory/model/recommender/insight/data.py
src/spaceone/inventory/model/recommender/recommendation/cloud_sevice_type.py

* Apply link processing between target resource of insight in recommender service
* Change resource_id of reference_key to name

Apply link processing between target resource of insight in recommender service

---

src/spaceone/inventory/manager/recommender/insight_manager.py

* Add change_resource_name method in insight manager

Add change_resource_name method in insight manager

---

README.md

* Add IAM guide to use Recommender service in README.md

Add IAM guide to use Recommender service in README.md

---

src/spaceone/inventory/libs/schema/cloud_service.py
src/spaceone/inventory/model/compute_engine/instance/data.py

Add data.log_support_providers for logging service

Add data.log_support_providers for logging service

---

src/spaceone/inventory/libs/schema/cloud_service.py
src/spaceone/inventory/model/compute_engine/instance/data.py

Modify data.support_providers for logging service

Modify data.support_providers for logging service

---

src/spaceone/inventory/libs/schema/cloud_service.py
src/spaceone/inventory/model/compute_engine/instance/data.py

Remove supported_providers

---

src/spaceone/inventory/manager/recommender/recommendation_manager.py
src/spaceone/inventory/model/recommender/recommendation/cloud_service.py
src/spaceone/inventory/model/recommender/recommendation/data.py

* change operations logic in recommender service

Change operations logic in recommender service

---

src/spaceone/inventory/libs/manager.py
src/spaceone/inventory/libs/schema/cloud_service.py
src/spaceone/inventory/manager/compute_engine/vm_instance_manager.py
src/spaceone/inventory/model/compute_engine/instance/data.py

* add google_cloud_logging field in BaseResource
* add google_cloud_logging field in VM instance' model

Add google_cloud_logging field in BaseResource

---

src/spaceone/inventory/libs/schema/google_cloud_logging.py

* add google_cloud_logging module in libs

Add google_cloud_logging module in libs

---

src/spaceone/inventory/model/recommender/recommendation/cloud_service.py
src/spaceone/inventory/model/recommender/recommendation/cloud_sevice_type.py

* Remove unnecessary columns from tables showing recommendation resources

Remove unnecessary columns from tables showing recommendation resources

---

src/spaceone/inventory/model/recommender/recommendation/cloud_service.py

* change reference_key of target resources `data.name` to `name` in recommender service

Change reference_key of target resources data.name to name in recommender service

---

src/spaceone/inventory/manager/recommender/recommendation_manager.py

* Improved logic for selecting target locations in recommender manager

Improved logic for selecting target locations in recommender manager

---

pkg/pip_requirements.txt
src/setup.py
src/spaceone/inventory/manager/recommender/recommendation_manager.py
src/spaceone/inventory/model/recommender/recommendation/cloud_service.py
src/spaceone/inventory/model/recommender/recommendation/data.py

* add human readable description of cost in recommend service
* add zones to parents' location parameter in recommender service

Add human readable description of cost in recommend service 

---

src/spaceone/inventory/manager/compute_engine/vm_instance/vm_instance_manager_resource_helper.py

* Fix get_labels method in vm_instance

Fix get_labels method in vm_instance

---

src/spaceone/inventory/manager/compute_engine/vm_instance/vm_instance_manager_resource_helper.py
src/spaceone/inventory/model/compute_engine/instance/cloud_service.py
src/spaceone/inventory/model/compute_engine/instance/data.py

* Add Tags Tab in compute engine service

Add Tags Tab in Vm instance of compute engine service

---

src/spaceone/inventory/manager/compute_engine/vm_instance/vm_instance_manager_resource_helper.py
src/spaceone/inventory/model/compute_engine/instance/cloud_service.py
src/spaceone/inventory/model/compute_engine/instance/data.py

* Add SSH key field in VM instance of tab

Add SSH key field in VM instance of tab

---

src/spaceone/inventory/manager/compute_engine/vm_instance/vm_instance_manager_resource_helper.py

* Add split argument because of bug

Add split argument because of bug

---

src/spaceone/inventory/manager/recommender/recommendation_manager.py
src/spaceone/inventory/model/recommender/recommendation/cloud_service.py
src/spaceone/inventory/model/recommender/recommendation/cloud_sevice_type.py
src/spaceone/inventory/model/recommender/recommendation/recommender_data.py

* Change the logic to determine the recommender's state

Change the logic to determine the recommender's state

---

src/spaceone/inventory/model/recommender/recommendation/cloud_service.py
src/spaceone/inventory/model/recommender/recommendation/cloud_sevice_type.py

* Change state color in recommend service

Change state color in recommend service

---

src/spaceone/inventory/manager/recommender/recommendation_manager.py

* add validation code of available locations when collecting recommender resources

Add validation code of available locations when collecting recommender resources

---

src/spaceone/inventory/manager/recommender/recommendation_manager.py

* change crawling logic of Recommender service

Change crawling logic of Recommender service

---

src/spaceone/inventory/manager/compute_engine/vm_instance_manager.py
src/spaceone/inventory/model/compute_engine/instance/cloud_service.py
src/spaceone/inventory/model/compute_engine/instance/cloud_service_type.py
src/spaceone/inventory/model/compute_engine/instance/data.py

Add variable of GPU information in Compute engine resource

Add variable of GPU information in Compute engine resource

---

src/spaceone/inventory/model/compute_engine/instance/cloud_service_type.py

change gpus variables in table

Change gpus variables in table

---

src/spaceone/inventory/model/compute_engine/instance/cloud_service_type.py

* Delete options in GPUs of compute engine resource

Delete options in GPUs of compute engine resource

---

src/spaceone/inventory/manager/compute_engine/vm_instance_manager.py
src/spaceone/inventory/model/compute_engine/instance/cloud_service.py
src/spaceone/inventory/model/compute_engine/instance/cloud_service_type.py
src/spaceone/inventory/model/compute_engine/instance/data.py

* Add total_gpu_count field in compute engine resource

Add total_gpu_count field in compute engine resource

---

src/spaceone/inventory/model/compute_engine/instance/cloud_service_type.py

* Change options of gpu settings in Compute Engine service

Change options of gpu settings in Compute Engine service

---

src/spaceone/inventory/manager/pub_sub/topic_manager.py

* Add cloud logging code in Topic resource of Cloud Pub/Sub
* Because it is a simple code, code review was omitted.

Add cloud logging code in Topic resource of Cloud Pub/Sub

---

src/spaceone/inventory/conf/cloud_service_conf.py
src/spaceone/inventory/libs/manager.py
src/spaceone/inventory/manager/pub_sub/subscription_manager.py
src/spaceone/inventory/manager/pub_sub/topic_manager.py

* Refactor cloud logging in Topic resource of Cloud Pub/Sub
* Add cloud logging code in Subscription resource of Cloud Pub/Sub

refactor add_cloud_logging and add cloud logging in Subscription resource in Cloud Pub/Sub

---

src/spaceone/inventory/libs/manager.py
src/spaceone/inventory/manager/compute_engine/vm_instance_manager.py
src/spaceone/inventory/manager/pub_sub/snapshot_manager.py
src/spaceone/inventory/manager/pub_sub/subscription_manager.py
src/spaceone/inventory/manager/pub_sub/topic_manager.py

* refactor cloud logging in manager
* add cloud logging in snapshot resource of Cloud Pub/Sub
**Cloud logging can be used in each manager implementation with the code below.**
```python
topic.update({
'google_cloud_logging': self.set_google_cloud_logging(
'Pub/Sub', 'Topic', project_id, topic_name
)
})
```

refactor cloud logging in manager and add cloud logging in snapshot resource of Cloud Pub/Sub

---

src/spaceone/inventory/conf/cloud_service_conf.py
src/spaceone/inventory/manager/cloud_functions/function_gen1_manager.py
src/spaceone/inventory/manager/cloud_functions/function_gen2_manager.py
src/spaceone/inventory/manager/cloud_storage/storage_manager.py

* Add cloud logging in Function resource of Cloud Functions
* Add cloud logging in Bucket resource of Cloud Storage

Add cloud logging in Function resource of Cloud Functions and Bucket resource of Cloud Storage

---

src/spaceone/inventory/conf/cloud_service_conf.py
src/spaceone/inventory/manager/cloud_sql/instance_manager.py
src/spaceone/inventory/manager/compute_engine/disk_manager.py
src/spaceone/inventory/manager/compute_engine/instance_group_manager.py
src/spaceone/inventory/manager/compute_engine/instance_template_manager.py
src/spaceone/inventory/manager/compute_engine/machine_image_manager.py

* Add cloud logging in Instance resource of Cloud SQL
* Add cloud logging in Resources of Compute Engine

Add cloud logging in Instance resource of Cloud SQL and resources of Compute Engine

---

src/spaceone/inventory/manager/compute_engine/vm_instance_manager.py

* Remove duplicated logging code in vm_instance_manager

Remove duplicated logging code in vm_instance_manager

---

src/spaceone/inventory/manager/cloud_functions/function_gen1_manager.py
src/spaceone/inventory/manager/cloud_functions/function_gen2_manager.py

Add NotFound Exception when not using GCS in cloud functions

Add NotFound Exception when not using GCS in cloud functions

---

src/spaceone/inventory/manager/recommender/recommendation_manager.py
src/spaceone/inventory/model/recommender/recommendation/data.py
test/api/test_cloudservice_api.py

* Modify overview schema in recommender service

Modify overview schema in recommender service

---

src/spaceone/inventory/libs/manager.py
src/spaceone/inventory/libs/schema/cloud_service.py
src/spaceone/inventory/service/collector_service.py

* Add SKIP status in resource because of Disabled service

Add SKIP status in resource because of Disabled service

---

src/spaceone/inventory/libs/manager.py
src/spaceone/inventory/libs/schema/cloud_service.py

* Change SKIP logic in manager because of Disabled service

Change SKIP logic in manager because of Disabled service

---

src/spaceone/inventory/libs/manager.py

* Fix SKIP logic in manager because of Disabled service

Fix SKIP logic in manager because of Disabled service

---

src/spaceone/inventory/conf/cloud_service_conf.py
src/spaceone/inventory/connector/resource_manager/project.py
src/spaceone/inventory/manager/cloud_functions/function_gen1_manager.py
src/spaceone/inventory/manager/cloud_functions/function_gen2_manager.py
src/spaceone/inventory/model/cloud_functions/function_gen1/cloud_service.py
src/spaceone/inventory/model/cloud_functions/function_gen1/data.py
src/spaceone/inventory/model/cloud_functions/function_gen2/cloud_service.py
src/spaceone/inventory/model/cloud_functions/function_gen2/data.py
src/spaceone/inventory/service/collector_service.py

* Add project check logic in collect method

Add project check logic in collect method

---

src/spaceone/inventory/manager/cloud_functions/function_gen2_manager.py

* modify memory allocated logic in cloud functions service

Modify memory allocated logic in cloud functions service

---

src/spaceone/inventory/conf/cloud_service_conf.py
src/spaceone/inventory/connector/bigquery/sql_workspace.py
src/spaceone/inventory/manager/bigquery/sql_workspace_manager.py
src/spaceone/inventory/model/bigquery/sql_workspace/cloud_service.py
src/spaceone/inventory/model/bigquery/sql_workspace/cloud_service_type.py
src/spaceone/inventory/model/bigquery/sql_workspace/data.py
test/api/test_cloudservice_api.py

* Modify collecting methods of datasets and tables
* Apply black formatter

Modify collecting methods of datasets and tables in BigQuery service

---

src/spaceone/inventory/connector/bigquery/sql_workspace.py
src/spaceone/inventory/manager/bigquery/sql_workspace_manager.py
src/spaceone/inventory/model/bigquery/sql_workspace/cloud_service.py
src/spaceone/inventory/model/bigquery/sql_workspace/data.py

* Remove list projects method in Bigquery service

Remove list projects method in Bigquery service

---

.gitignore
src/setup.py
src/spaceone/inventory/metrics/ComputeEngine/Instance/instance_count.yaml
src/spaceone/inventory/metrics/ComputeEngine/Instance/memory_size.yaml
src/spaceone/inventory/metrics/ComputeEngine/Instance/namespace.yaml
src/spaceone/inventory/metrics/ComputeEngine/Instance/vcpu_count.yaml
src/spaceone/inventory/service/collector_service.py

- [*] Improvement
* Apply collect metrics method when collecting cloud resources

Apply collect metrics method when collecting cloud resources

---

src/spaceone/inventory/metrics/BigQuery/SQLWorkspace/namespace.yaml
src/spaceone/inventory/metrics/CloudFunctions/Function/namespace.yaml
src/spaceone/inventory/metrics/CloudSQL/Instance/namespace.yaml
src/spaceone/inventory/metrics/CloudStorage/Bucket/namespace.yaml
src/spaceone/inventory/metrics/ComputeEngine/Instance/instance_count.yaml
src/spaceone/inventory/metrics/ComputeEngine/Instance/memory_size.yaml
src/spaceone/inventory/metrics/ComputeEngine/Instance/namespace.yaml
src/spaceone/inventory/metrics/ComputeEngine/Instance/vcpu_count.yaml
src/spaceone/inventory/metrics/Networking/ExternalIPAddress/namespace.yaml
src/spaceone/inventory/metrics/Networking/Firewall/namespace.yaml
src/spaceone/inventory/metrics/Networking/LoadBalancing/namespace.yaml
src/spaceone/inventory/metrics/Networking/Route/namespace.yaml
src/spaceone/inventory/metrics/Networking/VPCNetwork/namespace.yaml
src/spaceone/inventory/metrics/PubSub/Schema/namespace.yaml
src/spaceone/inventory/metrics/PubSub/Snapshot/namespace.yaml
src/spaceone/inventory/metrics/PubSub/Subscription/namespace.yaml
src/spaceone/inventory/metrics/PubSub/Topic/namespace.yaml

Add namespace yaml files

---

src/spaceone/inventory/metrics/BigQuery/SQLWorkspace/namespace.yaml
src/spaceone/inventory/metrics/CloudFunctions/Function/namespace.yaml
src/spaceone/inventory/metrics/CloudSQL/Instance/namespace.yaml
src/spaceone/inventory/metrics/CloudStorage/Bucket/namespace.yaml
src/spaceone/inventory/metrics/ComputeEngine/Instance/instance_count.yaml
src/spaceone/inventory/metrics/ComputeEngine/Instance/memory_size.yaml
src/spaceone/inventory/metrics/ComputeEngine/Instance/namespace.yaml
src/spaceone/inventory/metrics/ComputeEngine/Instance/vcpu_count.yaml
src/spaceone/inventory/metrics/Networking/ExternalIPAddress/namespace.yaml
src/spaceone/inventory/metrics/Networking/Firewall/namespace.yaml
src/spaceone/inventory/metrics/Networking/LoadBalancing/namespace.yaml
src/spaceone/inventory/metrics/Networking/Route/namespace.yaml
src/spaceone/inventory/metrics/Networking/VPCNetwork/namespace.yaml
src/spaceone/inventory/metrics/PubSub/Schema/namespace.yaml
src/spaceone/inventory/metrics/PubSub/Snapshot/namespace.yaml
src/spaceone/inventory/metrics/PubSub/Subscription/namespace.yaml
src/spaceone/inventory/metrics/PubSub/Topic/namespace.yaml

Modify namespace yaml files

---

src/spaceone/inventory/manager/cloud_functions/function_gen1_manager.py
src/spaceone/inventory/manager/cloud_functions/function_gen2_manager.py
src/spaceone/inventory/metrics/CloudFunctions/Function/function_count.yaml
src/spaceone/inventory/metrics/CloudFunctions/Function/function_memory_size.yaml
src/spaceone/inventory/model/cloud_functions/function_gen1/data.py
src/spaceone/inventory/model/cloud_functions/function_gen2/data.py

* Add Metric yaml files of Cloud Functions service

Add Metric yaml files of Cloud Functions service

---

src/spaceone/inventory/manager/cloud_sql/instance_manager.py
src/spaceone/inventory/metrics/CloudSQL/Instance/database_count.yaml
src/spaceone/inventory/metrics/CloudSQL/Instance/instance_count.yaml
src/spaceone/inventory/metrics/CloudSQL/Instance/user_count.yaml
src/spaceone/inventory/model/cloud_sql/instance/data.py

* Add Metric yaml files of Cloud SQL service

Add Metric yaml files of Cloud SQL service

---

src/spaceone/inventory/conf/cloud_service_conf.py
src/spaceone/inventory/manager/compute_engine/vm_instance_manager.py
src/spaceone/inventory/manager/pub_sub/schema_manager.py
src/spaceone/inventory/manager/pub_sub/snapshot_manager.py
src/spaceone/inventory/manager/pub_sub/subscription_manager.py
src/spaceone/inventory/manager/pub_sub/topic_manager.py
src/spaceone/inventory/metrics/BigQuery/SQLWorkspace/table_count.yaml
src/spaceone/inventory/metrics/CloudSQL/Instance/database_count.yaml
src/spaceone/inventory/metrics/CloudSQL/Instance/user_count.yaml
src/spaceone/inventory/metrics/CloudStorage/Bucket/bucket_count.yaml
src/spaceone/inventory/metrics/PubSub/Schema/schema_count.yaml
src/spaceone/inventory/metrics/PubSub/Snapshot/snapshot_count.yaml
src/spaceone/inventory/metrics/PubSub/Subscription/subscription_count.yaml
src/spaceone/inventory/metrics/PubSub/Topic/subscription_count.yaml
src/spaceone/inventory/metrics/PubSub/Topic/topic_count.yaml
src/spaceone/inventory/model/compute_engine/instance/data.py
src/spaceone/inventory/model/pub_sub/schema/cloud_service.py
src/spaceone/inventory/model/pub_sub/schema/cloud_service_type.py
src/spaceone/inventory/model/pub_sub/snapshot/cloud_service.py
src/spaceone/inventory/model/pub_sub/snapshot/cloud_service_type.py
src/spaceone/inventory/model/pub_sub/subscription/cloud_service.py
src/spaceone/inventory/model/pub_sub/subscription/cloud_service_type.py
src/spaceone/inventory/model/pub_sub/topic/cloud_service.py
src/spaceone/inventory/model/pub_sub/topic/cloud_service_type.py
src/spaceone/inventory/model/pub_sub/topic/data.py
test/api/test_cloudservice_api.py

* Add Metric yaml files of Pub/Sub service
* change pub/sub service name from Pub/Sub to PubSub

Add Metric yaml files of Pub/Sub service

---

src/spaceone/inventory/manager/networking/firewall_manager.py
src/spaceone/inventory/manager/networking/route_manager.py
src/spaceone/inventory/metrics/Networking/ExternalIPAddress/eip_count.yaml
src/spaceone/inventory/metrics/Networking/Firewall/firewall_count.yaml
src/spaceone/inventory/metrics/Networking/Firewall/instance_count.yaml
src/spaceone/inventory/metrics/Networking/LoadBalancing/loadbalancing_count.yaml
src/spaceone/inventory/metrics/Networking/Route/instance_count.yaml
src/spaceone/inventory/metrics/Networking/Route/route_count.yaml
src/spaceone/inventory/model/networking/firewall/data.py
src/spaceone/inventory/model/networking/load_balancing/data.py
test/api/test_cloudservice_api.py

* Add metric yaml files of Networking service

Add metric yaml files of Networking service

---

src/spaceone/inventory/manager/compute_engine/vm_instance_manager.py
src/spaceone/inventory/metrics/ComputeEngine/Disk/disk_count.yaml
src/spaceone/inventory/metrics/ComputeEngine/Disk/namespace.yaml
src/spaceone/inventory/metrics/ComputeEngine/Disk/read_iops_count.yaml
src/spaceone/inventory/metrics/ComputeEngine/Disk/write_iops_count.yaml
src/spaceone/inventory/metrics/ComputeEngine/InstanceGroup/instance_count.yaml
src/spaceone/inventory/metrics/ComputeEngine/InstanceGroup/instance_group_count.yaml
src/spaceone/inventory/metrics/ComputeEngine/InstanceGroup/namespace.yaml
src/spaceone/inventory/metrics/ComputeEngine/InstanceTemplate/instance_template_count.yaml
src/spaceone/inventory/metrics/ComputeEngine/InstanceTemplate/namespace.yaml
src/spaceone/inventory/metrics/ComputeEngine/MachineImage/machine_image_count.yaml
src/spaceone/inventory/metrics/ComputeEngine/MachineImage/namespace.yaml
src/spaceone/inventory/metrics/Networking/Route/instance_count.yaml
src/spaceone/inventory/metrics/Networking/Route/route_count.yaml
src/spaceone/inventory/metrics/Networking/VPCNetwork/firewall_count.yaml
src/spaceone/inventory/metrics/Networking/VPCNetwork/namespace.yaml
src/spaceone/inventory/metrics/Networking/VPCNetwork/route_count.yaml
src/spaceone/inventory/metrics/Networking/VPCNetwork/subnet_count.yaml
src/spaceone/inventory/metrics/Networking/VPCNetwork/vpc_count.yaml
test/api/test_cloudservice_api.py

Add metric yaml files

---

src/spaceone/inventory/metrics/ComputeEngine/Disk/write_iops_count.yaml

Modify metric yaml file

---

src/spaceone/inventory/conf/cloud_service_conf.py
src/spaceone/inventory/manager/cloud_storage/storage_manager.py

* Add europe-central2 region in config file

Add europe-central2 region in config file

---

src/spaceone/inventory/service/collector_service.py

fix: delete metric yaml files

---

src/spaceone/inventory/model/compute_engine/instance/cloud_service.py

* Change word MAx to Max in compute engine model

Change word MAx to Max in compute engine model

---

src/spaceone/inventory/manager/compute_engine/disk_manager.py
src/spaceone/inventory/metrics/ComputeEngine/Disk/disk_count.yaml
src/spaceone/inventory/model/compute_engine/disk/data.py

- add in_used_by_count field at Disk of ComputeEngine

Add in_used_by_count field at Disk of ComputeEngine

---

src/spaceone/inventory/manager/cloud_functions/function_gen2_manager.py

correct string formatting in ingress settings readability function

---

src/spaceone/inventory/manager/cloud_storage/storage_manager.py

-  comment out IAM policy retrieval in storage manager

fix: comment out IAM policy retrieval in storage manager

---

src/spaceone/inventory/connector/resource_manager/project.py
src/spaceone/inventory/service/collector_service.py

- [o] Improvement
- fix: add error handling in get_project_info and improve logging in collector_service

fix: add error handling in get_project_info and improve logging in collector_service
